//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ji
{
    using System;
    using System.Collections.Generic;
    
    public partial class BillDetail
    {
        public int ID { get; set; }
        public int BillID { get; set; }
        public string FoodName { get; set; }
        public int PriceFood { get; set; }
        public string ToppingName { get; set; }
        public Nullable<int> PriceTopping { get; set; }
    
        public virtual Bills Bills { get; set; }
    }
}
