//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ji
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public int ID { get; set; }
        public string FacName { get; set; }
        public string Phone { get; set; }
        public string Address { get; set; }
        public int CustomerID { get; set; }
        public string Slogan { get; set; }
        public string MemberShip { get; set; }
        public string MAC_Address { get; set; }
    
        public virtual L_Customer L_Customer { get; set; }
    }
}
