//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ji
{
    using System;
    
    public partial class ji_Printing_Result1
    {
        public Nullable<int> cIndex { get; set; }
        public string CustomerName { get; set; }
        public string Cashier { get; set; }
        public Nullable<System.DateTime> TimeCheckout { get; set; }
        public string FoodName { get; set; }
        public string Topping { get; set; }
        public Nullable<int> Quantity { get; set; }
        public string Money { get; set; }
        public string TotalMoney { get; set; }
        public string MoneyCustomer { get; set; }
        public string CustomerRefund { get; set; }
        public Nullable<int> Floor { get; set; }
        public Nullable<int> Table { get; set; }
        public string Total { get; set; }
        public Nullable<int> BillID { get; set; }
    }
}
