//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ji
{
    using System;
    using System.Collections.Generic;
    
    public partial class JiApplication
    {
        public int ID { get; set; }
        public string Category { get; set; }
        public string Name { get; set; }
        public System.DateTime CreateOn { get; set; }
        public int CreateBy { get; set; }
        public string DLL { get; set; }
        public string ClassName { get; set; }
        public string Image { get; set; }
        public string Version { get; set; }
        public string CategoryNonUnicode { get; set; }
        public string NameNonUnicode { get; set; }
        public string Install { get; set; }
        public bool DefaultDLL { get; set; }
    }
}
