//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ji
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_DateCome_Customer
    {
        public int ID { get; set; }
        public int CustomerID { get; set; }
        public int Come { get; set; }
        public int TotalMoney { get; set; }
        public System.DateTime CreateOn { get; set; }
    
        public virtual L_Customer L_Customer { get; set; }
    }
}
