//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ji
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_Floor
    {
        public string Name { get; set; }
        public int CountFloor { get; set; }
        public int CountTable { get; set; }
        public int Affect { get; set; }
        public bool Active { get; set; }
        public int ID { get; set; }
    }
}
