//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ji
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_History_Installer
    {
        public string NameDLL { get; set; }
        public string Version { get; set; }
        public string DLL { get; set; }
        public Nullable<System.DateTime> CreateOn { get; set; }
    }
}
