//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ji
{
    using System;
    using System.Collections.Generic;
    
    public partial class L_Topping
    {
        public int ID { get; set; }
        public int FacID { get; set; }
        public string ToppingName { get; set; }
        public int Price { get; set; }
        public string Image { get; set; }
        public int CreateBy { get; set; }
        public System.DateTime CreateOn { get; set; }
        public bool Active { get; set; }
        public int PriceInput { get; set; }
    }
}
